name: CI
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-22.04  # Use the default runner without a custom Docker container
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev libudev-dev ruby ruby-dev rubygems build-essential desktop-file-utils wget unzip zlib1g-dev liblzma-dev libssl-dev git imagemagick file libfuse2
        wget https://github.com/AppImage/pkg2appimage/archive/38603d92359a48189c35debad9005e8e902e6070.zip
        unzip *.zip
        sudo gem install --no-document fpm
    - name: Set up Python 3.6
      run: ./util/setup_python36.sh
    - name: Setup venv
      run: |
        ./util/python36/prefix/bin/python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
    - name: Build
      run: |
        . venv/bin/activate
        fbs freeze
        fbs installer
        deactivate
        ./pkg2appimage-*/pkg2appimage misc/Vial.yml
        mv out/Vial-*.AppImage out/Vial-x86_64.AppImage
    - uses: actions/upload-artifact@v4
      with:
        name: vial-linux
        path: out/Vial-x86_64.AppImage
  build-mac:
    runs-on: macos-14  # Updated from deprecated macos-11
    steps:
    - uses: actions/checkout@v4  # Updated to v4 for Node.js 20 support
    - uses: actions/setup-python@v5  # Much simpler than manual download
      with:
        python-version: '3.10.x'  # Minimum version available on macOS 14 ARM64
    - name: Setup venv
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Build
      run: |
        source venv/bin/activate
        fbs freeze
        hdiutil create -volname Vial -srcfolder "target/Curlton KeyStation.app" -ov -format UDZO vial-mac.dmg
    - uses: actions/upload-artifact@v4  # Updated to v4 for Node.js 20 support
      with:
        name: vial-mac
        path: vial-mac.dmg
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4  # Updated to v4 for Node.js 20 support
    
    - name: Install Visual C++ Redistributables
      run: |
        choco install vcredist2010 vcredist2012 --ignore-checksums -y
      shell: powershell
        
    - uses: actions/setup-python@v5  # Updated to v5 for Node.js 20 support
      with:
        python-version: '3.6.x'
    - name: Setup venv
      run: |
        python -m venv venv
        . .\venv\Scripts\activate.ps1
        python -m pip install --upgrade pip setuptools==45.2.0 wheel
        pip install "Cython>=0.29.0,<3.0.0"
        pip install hidapi==0.14.0
        pip install altgraph==0.17 fbs==0.9.0 future==0.18.2 keyboard==0.13.5 macholib==1.14 pefile==2019.4.18 PyInstaller==3.4 PyQt5==5.9.2 sip==4.19.8 certifi
        pip install "pywin32==303; sys_platform == 'win32'"
        pip install https://github.com/danthedeckie/simpleeval/archive/41c99b8e224a7a0ae0ac59c773598fe79a4470db.zip
    - name: Install NSIS
      run: |
        Invoke-WebRequest "https://github.com/vial-kb/vial-deps/releases/download/v1/nsis-3.06.1-setup.exe" -UserAgent "wget" -OutFile nsis-3.06.1-setup.exe
        if ((Get-FileHash nsis-3.06.1-setup.exe -Algorithm sha256).Hash -ne "f60488a676308079bfdf6845dc7114cfd4bbff47b66be4db827b89bb8d7fdc52") { Write-Error 'SHA256 mismatch' }
        Start-Process -FilePath "nsis-3.06.1-setup.exe" -ArgumentList "/S", "/D=C:\Program Files (x86)\NSIS" -NoNewWindow -Wait
    - name: Build
      run: |
        . .\venv\Scripts\activate.ps1
        fbs freeze
        Compress-Archive -Path "target\Curlton KeyStation" -DestinationPath vial-win.zip
    - uses: actions/upload-artifact@v4  # Updated to v4 for Node.js 20 support
      with:
        name: vial-win
        path: vial-win.zip
    - name: Create installer
      run: |
        $env:Path += ";C:\Program Files (x86)\NSIS"
        . .\venv\Scripts\activate.ps1
        fbs installer
    - uses: actions/upload-artifact@v4  # Updated to v4 for Node.js 20 support
      with:
        name: vial-win-installer
        path: target\Curlton KeyStationSetup.exe